language: ruby
cache: bundler
addons:
  apt:
    update: true
    packages:
    - sshpass
jobs:
  include:
  - stage: Test
    if: type = pull_request
    script:
    - bundle exec jekyll build
    - bundle exec htmlproofer ./_site
    - sshpass -e ssh -o StrictHostKeyChecking=no arichiv@ssh.ocf.berkeley.edu "mkdir -p public_html/__test__/${TRAVIS_PULL_REQUEST_BRANCH}"
    - sshpass -e scp -o StrictHostKeyChecking=no -r ./_site/* "arichiv@ssh.ocf.berkeley.edu:public_html/__test__/${TRAVIS_PULL_REQUEST_BRANCH}"
    - curl -u "${GITHUB_USER}:${GITHUB_TOKEN}" -X POST -d "{\"body\":\"[Test ${TRAVIS_BUILD_NUMBER}](https://www.ocf.berkeley.edu/~arichiv/__test__/${TRAVIS_PULL_REQUEST_BRANCH})\"}" "https://api.github.com/repos/${TRAVIS_REPO_SLUG}/issues/${TRAVIS_PULL_REQUEST}/comments"
  - stage: Deploy
    if: (type = push) AND (branch = master)
    script:
    - bundle exec jekyll build
    - sshpass -e scp -o StrictHostKeyChecking=no -r ./_site/* arichiv@ssh.ocf.berkeley.edu:public_html
