on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-ruby@master
    - name: Validate Site
      run: |
        bundle exec jekyll build
        bundle exec htmlproofer ./_site
